import { test } from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { openDatabase } from '../src/db.js';
import { createApp } from '../src/server.js';
import { runDue } from '../src/engine.js';
import { freshWorkspace } from '../public/marketing-tools.js';
import { scryptSync } from 'node:crypto';

test('authenticated HTTP journey, access controls, CSRF and exact approval', async t => {
  const db = openDatabase(':memory:');
  const origin = 'http://127.0.0.1:3101';
  const server = createApp({ db, origin });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); db.close(); });
  const base = `http://127.0.0.1:${server.address().port}`;
  function client() {
    let cookie = '', csrf = '';
    return async (path, method = 'GET', body, overrides = {}) => {
      const response = await fetch(`${base}${path}`, { method,
        headers: { Origin: origin, Cookie: cookie, 'X-CSRF-Token': csrf, 'Content-Type': 'application/json', ...overrides },
        ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
      if (response.headers.get('set-cookie')) cookie = response.headers.get('set-cookie').split(';')[0];
      const data = await response.json(); if (data?.csrf) csrf = data.csrf;
      return { status: response.status, data, headers: response.headers };
    };
  }
  const a = client(), b = client();
  assert.equal((await a('/api/campaigns')).status, 401);
  assert.equal((await a('/api/register', 'POST', { email: 'a@example.com', password: 'correct long password' })).status, 201);
  assert.equal((await b('/api/register', 'POST', { email: 'b@example.com', password: 'another long password' })).status, 201);
  const brand = { name: 'Test Brand', product: 'sales course', business: 'Sales courses', audience: 'business owners', tone: 'Clear', website: 'https://example.com', claims: '' };
  assert.equal((await a('/api/brand', 'PUT', brand, { Origin: 'https://attacker.example' })).status, 403);
  assert.equal((await a('/api/brand', 'PUT', brand, { 'X-CSRF-Token': 'invalid' })).status, 403);
  assert.equal((await a('/api/brand', 'PUT', brand)).status, 200);
  assert.equal((await b('/api/brand')).data, null);
  const missing = await a('/api/plan', 'POST', { message: 'Promote my course' });
  assert.deepEqual(missing.data.missing, ['budget', 'days']);
  const result = await a('/api/plan', 'POST', { message: 'Promote my sales course to Danish business owners for two weeks with 1,000 DKK' });
  assert.equal(result.status, 201);
  const c = result.data.campaign;
  assert.equal((await b(`/api/campaigns/${c.id}`)).status, 404);
  assert.equal((await b(`/api/campaigns/${c.id}/action`, 'POST', { action: 'submit', revision: 1 })).status, 404);
  assert.equal((await a(`/api/campaigns/${c.id}/action`, 'POST', { action: 'approve', revision: 1 })).status, 409);
  const edited = structuredClone(c.data); edited.items[0].content = '<script>alert(1)</script> factual draft';
  edited.items.forEach(item => item.due = Date.now() - 1000);
  const save = await a(`/api/campaigns/${c.id}`, 'PUT', { data: edited, revision: 1 });
  assert.equal(save.status, 200);
  assert.equal((await a(`/api/campaigns/${c.id}/action`, 'POST', { action: 'submit', revision: 2 })).data.status, 'awaiting approval');
  assert.equal((await a(`/api/campaigns/${c.id}/action`, 'POST', { action: 'approve', revision: 1 })).status, 409);
  assert.equal((await a(`/api/campaigns/${c.id}/action`, 'POST', { action: 'approve', revision: 2 })).data.status, 'scheduled');
  runDue(db); runDue(db);
  const done = await a(`/api/campaigns/${c.id}`);
  assert.equal(done.data.status, 'completed'); assert.equal(done.data.receipts.length, 3);
  assert.equal(done.data.receipts[0].content, edited.items[0].content);
  assert.equal(done.data.metrics.clicks, null);
  assert.ok(done.data.events.some(e => e.message.includes('completed')));
  assert.match(done.headers.get('content-security-policy'), /script-src 'self'/);
  const duplicate = await a(`/api/campaigns/${c.id}/duplicate`, 'POST', { revision: 2 });
  assert.equal(duplicate.status, 201); assert.equal(duplicate.data.status, 'draft');
  assert.equal(duplicate.data.jobs.length, 0); assert.equal(duplicate.data.receipts.length, 0);
  assert.equal(duplicate.data.approved_revision, null);
  assert.equal((await b(`/api/campaigns/${c.id}/duplicate`, 'POST', { revision: 2 })).status, 404);
  const product = { id: 'product-a', name: 'Course', description: 'Actual description', audience: 'Owners', website: '', offer: '', facts: '', cta: '', color: '#235a43' };
  const workspace = { ...freshWorkspace(), products: [product] };
  assert.equal((await a('/api/workspace', 'PUT', workspace)).data.revision, 1);
  assert.equal((await a('/api/workspace', 'PUT', workspace)).status, 409);
  assert.equal((await b('/api/workspace')).data.products.length, 0);
  await b('/api/workspace', 'PUT', { ...freshWorkspace(), products: [{ ...product, id: 'product-b', name: 'Other account product' }] });
  await b('/api/brand', 'PUT', brand);
  const otherCampaign = (await b('/api/plan', 'POST', { message: 'Promote my course for one week with 0 DKK' })).data.campaign;
  const backup = { format: 'marketing101-backup', version: 1, brand, workspace, campaigns: [{ id: c.id, data: done.data.data }] };
  const badBackup = { ...backup, workspace: { ...workspace, products: [{ ...product, website: 'javascript:alert(1)' }] } };
  assert.equal((await a('/api/restore', 'POST', badBackup)).status, 400);
  assert.equal((await a(`/api/campaigns/${c.id}`)).status, 200);
  assert.equal((await a('/api/validate-backup', 'POST', backup)).data.campaigns, 1);
  assert.equal((await a('/api/restore', 'POST', backup)).status, 200);
  const restored = (await a('/api/campaigns')).data;
  assert.equal(restored.length, 1); assert.equal(restored[0].status, 'draft'); assert.notEqual(restored[0].id, c.id);
  assert.equal((await a(`/api/campaigns/${restored[0].id}`)).data.jobs.length, 0);
  assert.equal((await b(`/api/campaigns/${otherCampaign.id}`)).status, 200);
  assert.equal((await b('/api/workspace')).data.products[0].name, 'Other account product');
  assert.equal((await a('/api/logout', 'POST', {})).status, 200);
  assert.equal((await a('/api/me')).status, 401);
  assert.equal((await a('/api/login', 'POST', { email: 'a@example.com', password: 'incorrect long password' })).status, 401);
  assert.equal((await a('/api/login', 'POST', { email: 'a@example.com', password: 'correct long password' })).status, 200);
  assert.equal((await a('/api/login', 'POST', { email: 'a@example.com', password: ' correct long password ' })).status, 401);
  const padded = client();
  assert.equal((await padded('/api/register', 'POST', { email: 'padded@example.com', password: '  exact padded password  ' })).status, 201);
  assert.equal((await padded('/api/logout', 'POST', {})).status, 200);
  assert.equal((await padded('/api/login', 'POST', { email: 'padded@example.com', password: 'exact padded password' })).status, 401);
  assert.equal((await padded('/api/login', 'POST', { email: 'padded@example.com', password: '  exact padded password  ' })).status, 200);
  const salt = '0123456789abcdef0123456789abcdef';
  db.prepare('INSERT INTO users(id,email,password) VALUES(?,?,?)').run('legacy-user', 'legacy@example.com', `${salt}:${scryptSync('legacy long password', salt, 64).toString('hex')}`);
  assert.equal((await client()('/api/login', 'POST', { email: 'legacy@example.com', password: ' legacy long password ' })).status, 200);
});
