// Optional UI verification. Install Playwright separately or set PLAYWRIGHT_MODULE
// to an existing Playwright module path. Runtime app has no dependency on it.
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const modulePath = process.env.PLAYWRIGHT_MODULE;
const { chromium } = await import(modulePath ? pathToFileURL(modulePath).href : 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.TEST_BROWSER_CHANNEL ? { channel: process.env.TEST_BROWSER_CHANNEL } : {}) });
const base = process.env.TEST_ORIGIN || 'http://127.0.0.1:3101';
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error' && !message.text().includes('401')) errors.push(message.text()); });
await mkdir('test-results', { recursive: true });
async function fits() { assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Page must fit viewport'); }
try {
  await page.goto(base);
  await page.getByRole('button', { name: 'New here? Create an account' }).click();
  await page.getByLabel('Email', { exact: true }).fill(`browser-${Date.now()}@example.com`);
  await page.getByLabel(/^Password/).fill('browser smoke password');
  await page.getByRole('button', { name: 'Create account →', exact: true }).click();
  await page.getByRole('heading', { name: 'Your marketing, in motion.' }).waitFor();
  await fits();
  await page.getByRole('button', { name: 'Set up your brand' }).click();
  await page.getByLabel('Business name', { exact: true }).fill('North Studio');
  await page.getByLabel('Main product or offer', { exact: true }).fill('sales course');
  await page.getByLabel('Business details', { exact: true }).fill('Practical sales training for small businesses.');
  await page.getByLabel('Default audience', { exact: true }).fill('Danish small-business owners');
  await page.getByLabel('Brand tone', { exact: true }).fill('Clear and friendly');
  await page.getByLabel(/^Website or product link/).fill('https://example.com/course');
  await page.getByLabel('One claim per line', { exact: true }).fill('Includes lessons on discovery conversations.');
  await page.getByRole('button', { name: 'Save brand profile →', exact: true }).click();
  await page.getByRole('heading', { name: 'What are we promoting?' }).waitFor();
  await page.getByLabel('Your campaign request', { exact: true }).fill('Promote my sales course to Danish small-business owners');
  await page.getByRole('button', { name: 'Build my campaign' }).click();
  await page.getByLabel(/^Total budget \(DKK\)/).fill('1000');
  await page.getByLabel('Duration (days)', { exact: true }).fill('14');
  await page.getByRole('button', { name: 'Build my campaign' }).click();
  await page.getByRole('heading', { name: 'The campaign brief' }).waitFor();
  await page.getByRole('button', { name: '↻ Regenerate', exact: true }).first().click();
  await page.getByText('Content variation regenerated. Review it before approving.').waitFor();
  const exact = '<script>window.marketing101Xss=true</script> My reviewed campaign content.';
  await page.getByLabel('Exact content', { exact: true }).first().fill(exact);
  assert.ok(await page.getByRole('button', { name: 'Review campaign →', exact: true }).isDisabled());
  await page.getByRole('button', { name: 'Schedule all pieces now for a quick demo ↗', exact: true }).click();
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await page.getByText('Changes saved. Review the latest campaign.').waitFor();
  await page.getByRole('button', { name: 'Review campaign →', exact: true }).click();
  const approve = page.getByRole('button', { name: 'Approve & schedule →', exact: true });
  await approve.waitFor(); assert.ok(await approve.isDisabled());
  await page.getByLabel('I reviewed every content piece, link, date, and allocation.', { exact: true }).check();
  await approve.click();
  await page.getByText('completed', { exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole('heading', { name: 'Demo delivery receipts', exact: true }).waitFor();
  assert.equal(await page.locator('.receipt').count(), 3);
  assert.equal(await page.locator('.receipt pre').first().textContent(), exact);
  assert.equal(await page.evaluate(() => window.marketing101Xss), undefined);
  await fits();
  await page.screenshot({ path: 'test-results/desktop-campaign.png', fullPage: true });
  await page.getByRole('button', { name: '← All campaigns', exact: true }).click();
  await page.screenshot({ path: 'test-results/desktop-overview.png', fullPage: true });
  await page.getByRole('button', { name: 'Automation', exact: true }).click();
  await page.getByLabel('Enable automatic mode for matching campaigns', { exact: true }).check();
  await page.getByLabel('Demo workspace', { exact: true }).check();
  await page.getByLabel('Product promotion', { exact: true }).check();
  await page.getByLabel('Maximum per campaign (DKK)', { exact: true }).fill('1000');
  await page.getByLabel(/^Maximum per day \(DKK\)/).fill('1000');
  await page.getByRole('button', { name: 'Save automation rules →', exact: true }).click();
  await page.getByText('Automation rules saved.').waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Your marketing, in motion.' }).waitFor();
  assert.equal(await page.locator('.campaign-row').count(), 1);
  await page.setViewportSize({ width: 390, height: 844 });
  await fits();
  await page.screenshot({ path: 'test-results/mobile-overview.png', fullPage: true });
  await page.locator('.campaign-row').click();
  await page.getByRole('heading', { name: 'The campaign brief' }).waitFor(); await fits();
  await page.screenshot({ path: 'test-results/mobile-campaign.png', fullPage: true });
  await page.getByRole('button', { name: 'Brand profile', exact: true }).click();
  await page.getByRole('heading', { name: 'Make it sound like you.' }).waitFor(); await fits();
  assert.equal(await page.getByLabel('Business name', { exact: true }).inputValue(), 'North Studio');
  await page.getByRole('button', { name: 'Create campaign', exact: true }).click(); await fits();
  await page.getByRole('button', { name: 'Automation', exact: true }).click(); await fits();
  assert.ok(await page.getByLabel('Enable automatic mode for matching campaigns', { exact: true }).isChecked());
  await page.getByRole('button', { name: 'Sign out ↗', exact: true }).click();
  await page.getByRole('heading', { name: 'Welcome back.', exact: true }).waitFor(); await fits();
  await page.screenshot({ path: 'test-results/mobile-signin.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('Browser smoke passed: registration, brand, missing fields, regeneration, editing, approval, worker delivery, persistence, automation, mobile layouts, XSS escaping, logout.');
} catch (error) {
  await page.screenshot({ path: 'test-results/failure.png', fullPage: true });
  console.error('Browser state:', await page.locator('h1,h2').allTextContents());
  console.error('Textarea labels:', await page.locator('textarea').evaluateAll(nodes => nodes.map(n => ({ name: n.name, label: n.labels?.[0]?.textContent }))));
  console.error('Browser errors:', errors);
  throw error;
} finally { await browser.close(); }
